### ISSUE TITLE
Writer always adds "exposing" to imports, even if nothing is exposed for that import

### ISSUE THREAD

**Issue by SidneyNemzer** [stil4m/elm-syntax#1]
Example:

https://ellie-app.com/4FG9sntQba1/4

Culprit:

https://github.com/stil4m/elm-syntax/blob/1.0.0/src/Elm/Writer.elm#L126

**Comment by stil4m** [comment]
Fixed with 20ec711e457dfb708d6395d3911e86b17be90114 and 5cbe41cbf8dcdf69f3b7b4b22849f543ec7b9fe3
