### ISSUE TITLE
Node.empty function

### ISSUE THREAD

**Issue by pravdomil** [stil4m/elm-syntax#115]
```elm
empty: a -> Node a
empty a = Node Range.emptyRange a
```
What do you think?

**Comment by MartinSStewart** [comment]
This could be a useful helper function. That said, in this issue https://github.com/stil4m/elm-syntax/issues/100 I discuss removing Node all together. Still, if that doesn't work out, I think this makes sense to have.

**Comment by jfmengels** [comment]
This was fixed back in 7.3.0.
