### ISSUE TITLE
CharLiteral doesn’t handle escapes correctly

### ISSUE THREAD

**Issue by NiavlysB** [stil4m/elm-syntax#124]
In [`writeExpression`](https://github.com/stil4m/elm-syntax/blob/609c0ee58c7ebf65628cea49bfd8044c0aff9fe5/src/Elm/Writer.elm#L496), the CharLiteral case doesn’t check if the character is an escape (backslash `\\` for instance).

        CharLiteral c ->
            string ("'" ++ String.fromList [ c ] ++ "'")

This seems to produce a syntax error in the generated Elm code, because the single-quote delimiters aren’t closed:

    '\'

It should probably also escape an actual tab to a `'\t'`, a `'→'` to a `'\u{2192}'`, etc.

**Comment by MartinSStewart** [comment]
Hello, I'll fix this over the weekend. That said, I recommend using elm-syntax-dsl instead of the built-in Elm.Writer. elm-syntax-dsl is more stable and generates better formatted code.

**Comment by NiavlysB** [comment]
I am actually using elm-syntax-dsl! But looking up the code I figured it was relying at the lowest lovel (char literal) on Elm.Writer. Maybe I’m wrong?

**Comment by MartinSStewart** [comment]
Maybe, I'll take a closer look when I go to fix this.

**Comment by NiavlysB** [comment]
Thanks!

**Comment by MartinSStewart** [comment]
This should be fixed now once a patch version of elm-syntax is released. Also I checked and I don't believe this bug affected elm-syntax-dsl as none of the modules in elm-syntax-dsl import Elm.Writer. It probably has its own implementation.

**Comment by NiavlysB** [comment]
Oh ok, I’ll have a closer look at elm-syntax-dsl then! Thanks!
