### ISSUE TITLE
Binary operator parsing precedence bug

### ISSUE THREAD

**Issue by wolfadex** [stil4m/elm-syntax#258]
**Describe the bug**
`a + b /= 0` is marked as invalid but the Elm compiler and elm-test don't have an issue with it. By wrapping the math in parens, like `(a + b) /= 0`, then it parses fine.  This also applies to `a + b + c /= 0` where wrapping like `(a + b  +c ) /= 0` fixes it.

**Additional context**
This was originally filed in elm-review https://github.com/jfmengels/elm-review/issues/177 as that's where the bug was found. Elm Slack thread for discussion reference https://elmlang.slack.com/archives/C010RT4D1PT/p1725977809992319.

**Comment by jfmengels** [comment]
Fixed in `7.3.6`
