### ISSUE TITLE
Elm.Parser incorrectly reports syntax errors

### ISSUE THREAD

**Issue by MartinSStewart** [stil4m/elm-syntax#26]
Calling Elm.Parser.parse on the Elm.Processing source file returns an Err result. This seems like a bug since if Elm.Processing really had a syntax error, I wouldn't be able to use this package in the first place.

**Code used to reproduce this behavior**
https://ellie-app.com/3NDQvRWHFrKa1

**Details**
The exact syntax error I get is 
```Err [{ col = 32, problem = ExpectingVariable, row = 190 },{ col = 32, problem = ExpectingVariable, row = 190 },{ col = 32, problem = ExpectingSymbol "\"", row = 190 },{ col = 32, problem = ExpectingSymbol "'", row = 190 },{ col = 32, problem = UnexpectedChar, row = 190 },{ col = 32, problem = ExpectingNumber, row = 190 },{ col = 32, problem = ExpectingSymbol "()", row = 190 },{ col = 32, problem = ExpectingSymbol "_", row = 190 },{ col = 32, problem = Expecting "{", row = 190 },{ col = 32, problem = Expecting "[", row = 190 },{ col = 32, problem = Expecting "(", row = 190 }]```

which seems to point to `(\( p, infix, s ) ->` in this code within Elm.Processing
```                findNextSplit ops exps
                    |> Maybe.map
                        (\( p, infix, s ) ->
                            OperatorApplication
                                (Node.value infix.operator)
                                (Node.value infix.direction)
                                (Node (Range.combine <| List.map Node.range p) (divideAndConquer p))
                                (Node (Range.combine <| List.map Node.range s) (divideAndConquer s))
                        )
                    |> Maybe.withDefault (fixExprs exps)
```

**Comment by stil4m** [comment]
When I open up the Ellie I get a valid parse. Is this thus resolved?

**Comment by MartinSStewart** [comment]
Yeah, it works for me too. I guess this got fixed at some point. I'll close this then.
