### ISSUE TITLE
Parsing error when function argument rec deconstruction is empty

### ISSUE THREAD

**Issue by shepelevstas** [stil4m/elm-syntax#42]
Hello! Thanks for the great tool! Superuseful!
```
foo : Point -> Point
foo ({} as p) = p
```
results in Parsing error, but happily compiles!

**Comment by sparksp** [comment]
Is this related to #39

**Comment by jfmengels** [comment]
This was fixed in https://github.com/stil4m/elm-syntax/pull/40
