### ISSUE TITLE
Simplify TypeAnnotation 

### ISSUE THREAD

**Issue by jfmengels** [stil4m/elm-syntax#49]
I think the [`TypeAnnotation`](https://package.elm-lang.org/packages/stil4m/elm-syntax/latest/Elm-Syntax-TypeAnnotation#TypeAnnotation) type could be simplified a bit.

[`elm/project-metadata-utils`](https://package.elm-lang.org/packages/elm/project-metadata-utils/1.0.1/Elm-Type#Type) provides a different representation for the same data (without the `Range`s).

In the following proposals, I will have a table of equivalences, where `<thing>` means that something is wrapped in a `Node`.

If you prefer discussing each one in different issues, let me know and I'll be happy to create them.

### Removing `Unit` in favor of `Tupled []`

| Elm code |elm-syntax|elm/project-metadata-utils|
| ------ | ------------- | ------------- |
|()| Unit | Tuple [] |
|( a, b )| Tupled [ <GenericType "a">, <GenericType "b">  ] | Tuple [ Var "a", Var "b" ] |

I think that the `Unit` serves little purpose, and could be simplified to `Tupled []`, like what `project-metadata-utils` does.

Changing this doesn't make pattern matching harder, as you can still pattern match for `Tupled []`.

### Fusing GenericRecord and Record

| Elm code |elm-syntax|elm/project-metadata-utils|
| ------ | ------------- | ------------- |
| { a : () } | Record [ <( <"a">, \<Unit> )> ] | Record [ ( "a", Tuple [] ) ] Nothing |
| { b \| a : () } | GenericRecord <"b"> [ <( <"a">, \<Unit> )> ] | Record [ ( "a", Tuple [] ) ] (Just "b") |

`elm/project-metadata-utils` employs the same type for records and generic records, and uses a `Maybe` for the optional generic part.
Both Record and GenericRecord serve similar purposes, and in practice I think that we will analyse them in similar ways. Having a single type can help avoid duplication of code.

Again, this does not prevent pattern matching directly on generic and non-generic record, as you can still pattern match for `Record _ Nothing` and `Record _ (Just _)`

Changing this doesn't make pattern matching harder, as you can still pattern match for `Tupled []`.

### Renaming `Tupled` to `Tuple` and `Typed` to `Type`

| Elm code |elm-syntax|elm/project-metadata-utils|
| ------ | ------------- | ------------- |
| a | GenericType "a"|Var "a"|
| Elm.Syntax.Node.Node a | Typed <( [ "Elm", "Syntax", "Node" ], "Node" )> [ <GenericType "a"> ] | Type "Elm.Syntax.Node.Node" [ Var "a" ]|

I think the terms chosen by `project-metadata-utils` are more like how people read them. I think people (at least I do) read type annotations like "It takes a type `Foo` and returns a tuple of `String` and `Int`", and not "It takes a typed `Foo` and returns a tupled `String` and `Int`.

I actually have a hard time figuring out how to read those types in `elm-syntax`.

Note: I think the `Typed` variant in `elm-syntax` is more useful than the `Type` from `project-metadata-utils` because splitting the module name from the function name can be very useful.

### Rename `GenericType` to `Var`

| Elm code |elm-syntax|elm/project-metadata-utils|
| ------ | ------------- | ------------- |
| a | GenericType "a"|Var "a"|

This is entirely subjective, but I think `Var` is nicer, or at least it gives the same meaning but with a shorter name. I also think it would be nicer to have similar names for both projects.

**Comment by stil4m** [comment]
Just merged this into master via #59.
