### ISSUE TITLE
`+1` is considered valid syntax

### ISSUE THREAD

**Issue by jfmengels** [stil4m/elm-syntax#62]
As shown (roughly) [here](https://ellie-app.com/99h2vY7LWsCa1), `+1` is parsed and considered as valid syntax, even though Elm rejects it with a syntax error.

It seems to be parsed as `OperationApplication "+" Right (Application []) (Int 1)`. The Application is obviously invalid, and I am not sure how this will turn out in v8, where it has become a non-empty list. Also, its range is the emptyRange (0,0,0,0).

`++1` also seems to compile even though it shouldn't.

**Comment by stil4m** [comment]
Fixed this. Both `+1` and `1+` (same for other operators) are not accepted as valid syntax anymore and will not be parsed.
