### ISSUE TITLE
Found Operator in syntactically incorrect Elm code

### ISSUE THREAD

**Issue by jfmengels** [stil4m/elm-syntax#75]
I found a case where we get a `Operator` element, but the code is not considered syntactically correct from Elm's point of view.

```elm
module TestModule exposing (..)

a = ( +)
```

The same applies for `a = (+ )` and `a = ( + )`.

[Interactive Ellie](https://ellie-app.com/9cqDd7R3ys6a1)

**Comment by MartinSStewart** [comment]
I tried writing a test for this on master but the test correctly failed to parse.
```elm
sample40 : String
sample40 =
    """module Foo exposing (..)

x =
  (+ )

"""
```
This issue seems to have been resolved already?
